version: 2
updates:

  # github actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    assignees:
      - "alcohol"

  # npm dependencies
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    assignees:
      - "alcohol"
    versioning-strategy: "increase"
    allow:
      - dependency-type: "all"
    groups:
      minor-patch:
        update-types:
          - "minor"
          - "patch"

  # composer dependencies
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "weekly"
    assignees:
      - "alcohol"
    versioning-strategy: "increase"
    allow:
      - dependency-type: "all"
    groups:
      minor-patch:
        update-types:
          - "minor"
          - "patch"
