name: phpunit

on: [push, pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:

  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: [8.4, 8.5]
        stability: [prefer-lowest, prefer-stable]
    name: PHP ${{ matrix.php }} - ${{ matrix.stability }}
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - name: setup php
        uses: shivammathur/setup-php@f3e473d116dcccaddc5834248c87452386958240 # 2.37.2
        with:
          php-version: ${{ matrix.php }}
          extensions: mbstring
          coverage: xdebug
      - name: setup problem matchers
        env:
          RUNNER_TOOL_CACHE: ${{ runner.tool_cache }}
        run: |
          echo "::add-matcher::${RUNNER_TOOL_CACHE}/php.json"
          echo "::add-matcher::${RUNNER_TOOL_CACHE}/phpunit.json"
      - name: determine composer cache directory
        id: composer-cache
        run: "echo \"directory=$(composer config cache-dir)\" >> $GITHUB_OUTPUT"
      - name: cache dependencies installed with composer
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: ${{ steps.composer-cache.outputs.directory }}
          key: php-${{ matrix.php-version }}-${{ matrix.stability }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ matrix.php }}-${{ matrix.stability }}-composer
      - env:
          COMPOSER_STABILITY: ${{ matrix.stability }}
        run: composer update "--${COMPOSER_STABILITY}" --prefer-dist --no-interaction
      - run: composer run test
